In [185]:
import numpy as np
import pandas as pd
import datetime
import yfinance as yf
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta

# For importing universal scripts
import sys
import os
# Go up two levels from the subfolder
sys.path.append(os.path.abspath(".."))
from indicators_returns import final_df #Universal script for indicator set and actuals
import importlib
import indicators_returns
importlib.reload(indicators_returns)
from indicators_returns import final_df
import gc
from sklearn.metrics import (fbeta_score, accuracy_score, f1_score, 
                             confusion_matrix, balanced_accuracy_score, recall_score, matthews_corrcoef, precision_score)
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV, train_test_split, StratifiedKFold
from xgboost import XGBClassifier
import math
import pickle
from sklearn.inspection import permutation_importance
from sklearn.model_selection import TimeSeriesSplit

tags = pd.read_csv('../Indicator_Selection_Pipeline/Finalization/tags_cons.csv') 

def extract(ticker, returns, lb, cat_cols_all, windows=[10, 25]):

    import os
    # point this at an existing directory in your project
    os.chdir('/Users/brettchase/Documents/Fracturion/Feature_Set_Construction_Testing')
    
    df = final_df(ticker, returns, lb)
    df = df.iloc[:-101].replace([np.inf, -np.inf], 0)#

    df = df.sort_index(ascending=True)
    # Exponential Moving Average
    ema_cols = {
        f"{col}_EMA{w}": df[col].ewm(span=w, adjust=False).mean()
        for w in windows
        for col in cat_cols_all
    }
    # 3) merge them back into one dict
    new_cols = {**ema_cols}

    # 4) concatenate onto your original df
    df = pd.concat([df, pd.DataFrame(new_cols, index=df.index)], axis=1)    
    df = df.sort_index(ascending=False)
    
    return df

lb = 8
returns = [5, 10, 15, 20, 25, 30]
raw_all = tags['Indicator'][tags['Type'] == 'Raw']
df = extract('QQQ', returns, lb, raw_all, windows=[10,25])

# By category × velocity
duration_slow = tags[(tags['Type'] == 'Raw') & (tags['Category'] == 'duration') & (tags['velocity_25_cat_local'] == 'slow')]['Indicator'].tolist()
duration_moderate = tags[(tags['Type'] == 'Raw') & (tags['Category'] == 'duration') & (tags['velocity_25_cat_local'] == 'moderate')]['Indicator'].tolist()
duration_fast = tags[(tags['Type'] == 'Raw') & (tags['Category'] == 'duration') & (tags['velocity_25_cat_local'] == 'fast')]['Indicator'].tolist()
trend_slow = tags[(tags['Type'] == 'Raw') & (tags['Category'] == 'trend') & (tags['velocity_25_cat_local'] == 'slow')]['Indicator'].tolist()
trend_moderate = tags[(tags['Type'] == 'Raw') & (tags['Category'] == 'trend') & (tags['velocity_25_cat_local'] == 'moderate')]['Indicator'].tolist()
trend_fast = tags[(tags['Type'] == 'Raw') & (tags['Category'] == 'trend') & (tags['velocity_25_cat_local'] == 'fast')]['Indicator'].tolist()
trend_ratio_slow = tags[(tags['Type'] == 'Raw') & (tags['Category'] == 'trend_ratio') & (tags['velocity_25_cat_local'] == 'slow')]['Indicator'].tolist()
trend_ratio_moderate = tags[(tags['Type'] == 'Raw') & (tags['Category'] == 'trend_ratio') & (tags['velocity_25_cat_local'] == 'moderate')]['Indicator'].tolist()
trend_ratio_fast = tags[(tags['Type'] == 'Raw') & (tags['Category'] == 'trend_ratio') & (tags['velocity_25_cat_local'] == 'fast')]['Indicator'].tolist()
volatility_slow = tags[(tags['Type'] == 'Raw') & (tags['Category'] == 'volatility') & (tags['velocity_25_cat_local'] == 'slow')]['Indicator'].tolist()
volatility_moderate = tags[(tags['Type'] == 'Raw') & (tags['Category'] == 'volatility') & (tags['velocity_25_cat_local'] == 'moderate')]['Indicator'].tolist()
volatility_fast = tags[(tags['Type'] == 'Raw') & (tags['Category'] == 'volatility') & (tags['velocity_25_cat_local'] == 'fast')]['Indicator'].tolist()
momentum_slow = tags[(tags['Type'] == 'Raw') & (tags['Category'] == 'momentum') & (tags['velocity_25_cat_local'] == 'slow')]['Indicator'].tolist()
momentum_moderate = tags[(tags['Type'] == 'Raw') & (tags['Category'] == 'momentum') & (tags['velocity_25_cat_local'] == 'moderate')]['Indicator'].tolist()
momentum_fast = tags[(tags['Type'] == 'Raw') & (tags['Category'] == 'momentum') & (tags['velocity_25_cat_local'] == 'fast')]['Indicator'].tolist()
lag_fast = tags[(tags['Type'] == 'Raw') & (tags['Category'] == 'momentum') & (tags['velocity_25_cat_local'] == 'fast')]['Indicator'].tolist()

,Date,Close,Past_Return_10,Past_Return_25,wr_100_10,wr_100_25,wr_50_10
2011,2025-10-02,605.729980,1,1,0.87,0.99,0.76
2010,2025-10-01,603.250000,1,1,0.87,0.99,0.76
2009,2025-09-30,600.369995,1,1,0.87,0.99,0.76
2008,2025-09-29,598.729980,1,1,0.87,0.99,0.76
2007,2025-09-26,595.969971,1,1,0.87,0.99,0.76
2006,2025-09-25,593.530029,1,1,0.87,0.99,0.76
2005,2025-09-24,596.099976,1,1,0.87,0.99,0.76
2004,2025-09-23,598.200012,1,1,0.87,0.98,0.76
2003,2025-09-22,602.200012,1,1,0.87,0.97,0.76
2002,2025-09-19,598.655945,1,1,0.87,0.96,0.76
2001,2025-09-18,594.630676,1,1,0.87,0.95,0.76
2000,2025-09-17,589.316833,1,1,0.87,0.94,0.76
1999,2025-09-16,590.495422,1,1,0.87,0.93,0.76
1998,2025-09-15,590.994873,1,1,0.87,0.92,0.76
1997,2025-09-12,585.980652,1,1,0.87,0.91,0.76
1996,2025-09-11,583.403687,1,1,0.87,0.90,0.76
1995,2025-09-10,580.027588,1,1,0.86,0.89,0.76
1994,2025-09-09,579.837830,1,1,0.85,0.88,0.76
1993,2025-09-08,578.199707,1,1,0.84,0.87,0.76
1992,2025-09-05,575.392944,1,1,0.83,0.86,0.76
1991,2025-09-04,574.563904,1,1,0.82,0.85,0.76
1990,2025-09-03,569.409912,1,1,0.81,0.84,0.76
1989,2025-09-02,564.965027,0,0,0.80,0.83,0.76
1988,2025-08-29,569.739563,0,1,0.80,0.83,0.78
1987,2025-08-28,576.411804,0,1,0.80,0.82,0.80
1986,2025-08-27,572.825928,0,1,0.80,0.81,0.82
1985,2025-08-26,571.946960,0,1,0.80,0.80,0.84
1984,2025-08-25,569.659607,0,1,0.80,0.79,0.86
1983,2025-08-22,571.307678,0,1,0.80,0.78,0.88
1982,2025-08-21,562.627808,0,1,0.80,0.77,0.90

In [167]:
def past_return(df, days):

    future_return = (df['Close'] - df['Close'].shift(-days)) / df['Close']

    if days >= 100:
        df[f'Return_{days}'] = np.where(
            future_return > 0.001, 1,
            np.where(future_return < -0.001, 0, np.nan)
        )
    else:
        df[f'Past_Return_{days}'] = (future_return > 0).astype(int)

    return df

dft = df.copy()
for r in returns: 
    new_df = past_return(dft, r)

In [171]:
new_df[['Date', 'Close', 'Past_Return_25']].head(50)

            Date       Close  Past_Return_25
2011  2025-10-02  605.729980               1
2010  2025-10-01  603.250000               1
2009  2025-09-30  600.369995               1
2008  2025-09-29  598.729980               1
2007  2025-09-26  595.969971               1
2006  2025-09-25  593.530029               1
2005  2025-09-24  596.099976               1
2004  2025-09-23  598.200012               1
2003  2025-09-22  602.200012               1
2002  2025-09-19  598.655945               1
2001  2025-09-18  594.630676               1
2000  2025-09-17  589.316833               1
1999  2025-09-16  590.495422               1
1998  2025-09-15  590.994873               1
1997  2025-09-12  585.980652               1
1996  2025-09-11  583.403687               1
1995  2025-09-10  580.027588               1
1994  2025-09-09  579.837830               1
1993  2025-09-08  578.199707               1
1992  2025-09-05  575.392944               1
1991  2025-09-04  574.563904               1
1990  2025-09-03  569.409912               1
1989  2025-09-02  564.965027               0
1988  2025-08-29  569.739563               1
1987  2025-08-28  576.411804               1
1986  2025-08-27  572.825928               1
1985  2025-08-26  571.946960               1
1984  2025-08-25  569.659607               1
1983  2025-08-22  571.307678               1
1982  2025-08-21  562.627808               1
1981  2025-08-20  565.244751               1
1980  2025-08-19  568.620850               1
1979  2025-08-18  576.441711               1
1978  2025-08-15  576.671509               1
1977  2025-08-14  579.218567               1
1976  2025-08-13  579.668030               1
1975  2025-08-12  579.378296               1
1974  2025-08-11  572.186646               1
1973  2025-08-08  573.884705               1
1972  2025-08-07  568.580872               1
1971  2025-08-06  566.663086               1
1970  2025-08-05  559.621277               1
1969  2025-08-04  563.446777               1
1968  2025-08-01  553.238647               1
1967  2025-07-31  564.355774               1
1966  2025-07-30  567.362305               1
1965  2025-07-29  566.603149               1
1964  2025-07-28  567.482117               1
1963  2025-07-25  565.714172               1
1962  2025-07-24  564.355774               1

In [98]:
windows = [50, 100, 200]
returns = [5, 10, 15, 20, 25, 30]

for r in returns:

    for window in windows:

        # use standard rolling for last 50 values
        df[f'wr_{window}_{r}'] = df[f"Return_{r}"].iloc[r:].sort_index(ascending=True).rolling(window).sum() / window
        df[f'wr_{window}_{r}'] = df[f'wr_{window}_{r}'].bfill()

In [62]:
tickerSymbol = 'QQQ'
lb = 8

# Get data on this ticker
tickerData = yf.Ticker(tickerSymbol)
start_date = (datetime.today() - relativedelta(years=lb)).strftime('%Y-%m-%d')

tickerDf = tickerData.history(period='1d', start=start_date)

# Resetting the index will turn the Date index into a column
df_sma = tickerDf.reset_index()[['Date', 'Close', 'High', 'Low', 'Volume']]

# Convert the Date column to 'YYYY-MM-DD' format (if not already)
df_sma['Date'] = pd.to_datetime(df_sma['Date']).dt.strftime('%Y-%m-%d')

df = df_sma.sort_index(ascending=True)

In [63]:
df

            Date       Close        High         Low    Volume
0     2017-10-02  138.048904  138.608379  137.432521  27351300
1     2017-10-03  138.342834  138.504038  137.925594  19715200
2     2017-10-04  138.475601  138.769562  137.944573  26381100
3     2017-10-05  139.831665  139.907514  138.835980  31562400
4     2017-10-06  140.021332  140.021332  139.357547  23561100
...          ...         ...         ...         ...       ...
2007  2025-09-26  595.969971  596.299988  591.059998  54337400
2008  2025-09-29  598.729980  602.049988  597.409973  48332900
2009  2025-09-30  600.369995  600.710022  596.099976  46533800
2010  2025-10-01  603.250000  603.789978  596.340027  46899600
2011  2025-10-02  605.729980  607.114990  602.929993  38286914

[2012 rows x 5 columns]